
a = str("Hello World")
b = int(20)
c = float(1.2)
d = complex(1j)
e = list(("apple", "banana", "orange"))
f = tuple(("papaya", "cherry", "avocado"))
g = range(1,10,2)
h = dict(name = "John", age = 27)
i = set(("Melon", "Papaya", "Tomato"))
j = frozenset(("pizza", "burger", "noodles"))
k = bool(5)
l = bytes(5)
m = bytearray(5)
n = memoryview(bytes(5))

print(f"Item a is: {a}")
print(f"Item b is: {b}")
print(f"Item c is: {c}")
print(f"Item d is: {d}")
print(f"Item e is: {e}")
print(f"Item f is: {f}")
print(f"Item g is: {g}")
print(f"Item h is: {h}")
print(f"Item i is: {i}")
print(f"Item j is: {j}")
print(f"Item k is: {k}")
print(f"Item l is: {l}")
print(f"Item m is: {m}")
print(f"Item n is: {n}")

